git:
  depth: false

os:
  - linux

branches:
  only:
  - master

jobs:
  include:
    # ANACONDA
    - language: generic
      before_install:
        - export PATH="$HOME/miniconda3/bin:$PATH"
        - export CONDA_PY=36
      install: scripts/ci/install.sh
      script: pytest --cov=intake
      after_success:
        - coveralls
    # PYTHON
    - language: python
      dist: bionic
      python: "3.7"
      install:
        - sudo apt update
        - sudo apt install libsnappy-dev
        - pip install panel bokeh dask pytest zarr aiohttp requests
        - pip install -e .[complete]
      script:
        - pytest
    - language: python
      dist: bionic
      python: "3.8"
      install:
        - sudo apt update
        - sudo apt install libsnappy-dev
        - pip install panel bokeh dask pytest zarr aiohttp requests
        - pip install -e .[complete]
      script:
        - pytest

notifications:
  email: false
