{% set data = load_setup_py_data() %}

package:
   name: intake
   version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
   path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - numpy
    - pandas
    - msgpack-python
    - msgpack-numpy
    - requests
    - tornado
    - jinja2
    - ruamel_yaml >=0.15.0
    - dask >=0.17.0
    - python-snappy
    - appdirs

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - intake list -h
    - intake-server -h
    - py.test --pyargs -v intake

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_file: LICENSE
  summary: {{ data['description'] }}
