name: intake
channels:
  - defaults
  - conda-forge

dependencies:
  - appdirs=1.4.3
  - python=3.7
  - dask=2.10.1
  - numpy=1.18.1
  - pandas=1.0.1
  - msgpack-python=0.6.2
  - msgpack-numpy=0.4.4.3
  - requests=2.22.0
  - tornado=6.0.3
  - jinja2=2.11.1
  - python-snappy=0.5.4
  - pyyaml=5.3
  - hvplot=0.5.2
  - sphinx=2.4.0
  - sphinx_rtd_theme=0.4.3
  - numpydoc=0.9.2
  - panel=0.8.0
