name: intake
channels:
  - defaults
  - intake
  - conda-forge

dependencies:
  - appdirs
  - python=3.6
  - dask
  - numpy
  - pandas
  - msgpack-python
  - msgpack-numpy
  - requests
  - tornado
  - jinja2
  - ruamel_yaml >=0.15.0
  - dask >=0.17.0
  - python-snappy
  - holoplot
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - numpydoc
