name: intake
channels:
  - defaults

dependencies:
  - appdirs
  - python=3.7
  - dask=2.10.1
  - numpy
  - pandas
  - msgpack-python
  - msgpack-numpy
  - requests
  - tornado
  - jinja2
  - python-snappy
  - pyyaml
  - hvplot
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - panel => 0.8.0
