name: intake
channels:
  - defaults
  - conda-forge

dependencies:
  - appdirs
  - cloudpickle
  - python=3.6
  - dask
  - numpy
  - pandas
  - msgpack-python
  - msgpack-numpy
  - requests
  - tornado
  - jinja2
  - dask >=0.17.0
  - python-snappy
  - pyyaml
  - hvplot >=0.5.2
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - panel >=0.7.0
