name: intake
channels:
  - defaults
  - conda-forge

dependencies:
  - appdirs=1.4.3
  - python=3.7
  - dask=2.10.1
  - numpy=1.18.1
  - pandas=1.0.1
  - msgpack-python=0.6.2
  - msgpack-numpy=0.4.4.3
  - requests=2.22.0
  - tornado=6.0.3
  - jinja2=2.11.1
  - python-snappy
  - pyyaml
  - hvplot
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - panel=0.8.0
